### ISSUE TITLE
Resource system (EnTT?)

### ISSUE THREAD

**Issue by therealnv6** [therealnv6/ogl#1]
https://github.com/therealnv6/ogl/blob/9ddf619284b9e31e513271eb2a3d00cced65458f/src/main.cpp#L140
Not sure how I'm supposed to make references to resources (e.g., the camera as shown as above). I only need a single instance, and I feel like making a view then calling .front() on the first entity it finds is a bit verbose. Is there a better way to do this using EnTT? I found https://github.com/skypjack/entt/wiki/Crash-Course:-resource-management, however I wasn't sure if that's what I'm looking for.

**Comment by therealnv6** [comment]
For performance: I doubt it matters much. It just pulls the first entity out of the view. Is the view pre-queried? Or does it query it once you start the loop? I'd imagine it just queries it once the view is actually queried. Will do some testing in a second to make sure this is the case.

**Comment by pcranaway** [comment]
thank you very much

**Comment by therealnv6** [comment]
Resolved this a while ago, figured out [`context variables`](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#context-variables) are the equivalent I was looking for. Edited everything accordingly.
